### ISSUE TITLE
torch.Size

### ISSUE THREAD

**Issue by Aliraheem** [bronichern/DeepFry#1]
Hi! Can you help me to fix the error?

ali@1636126c3e10:~/DeepFry$ python run.py --data_dir /home/ali/DeepFry/CustomDataDIR/ --model_name /home/ali/DeepFry/models/CREAK-74lr_0.001_decay_38_input_size_128_hidden_size_256_channels_512_normalize_False_measure_ff1_dropout_0.1_classes_3_logtxt_ff1_.pth  --custom  --workers 4                                  loading model with params :{'input_size': 128, 'channels': 512, 'hidden_size': 256, 'classes': 3, 'enc_out_div': 1, 'enc_hidden': 128}
dataset length:72648
Traceback (most recent call last):
  File "run.py", line 74, in <module>
    main(args)
  File "run.py", line 45, in main
    train.test_textgrids(test_loader, test_model, criterion, device,args.window_size, args.output_dir, tv=args.tv,tc=args.tc)
  File "/home/ali/DeepFry/multi_train.py", line 70, in test_textgrids
    test_loader, model, criterion, device, tv, tc)
  File "/home/ali/DeepFry/multi_train.py", line 34, in create_predictions
    current_output[:, 1], current_creaky_label)
  File "/home/ali/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ali/.local/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 603, in forward
    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
  File "/home/ali/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 2908, in binary_cross_entropy
    "Please ensure they have the same size.".format(target.size(), input.size())
ValueError: Using a target size (torch.Size([43])) that is different to the input size (torch.Size([42])) is deprecated. Please ensure they have the same size.

**Comment by bronichern** [comment]
Hey,
We fixed it, you can check the latest version.
